name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (leave empty for latest)'
        required: false
        type: string

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        print-hash: true

    - name: Create GitHub release notes
      if: github.event_name == 'release'
      run: |
        echo "## 📦 PyPI Release" >> $GITHUB_STEP_SUMMARY
        echo "- **Package**: fs-git-mcp" >> $GITHUB_STEP_SUMMARY
        echo "- **Version**: ${{ github.event.release.tag_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **PyPI URL**: https://pypi.org/project/fs-git-mcp/" >> $GITHUB_STEP_SUMMARY
        echo "- **Release**: ${{ github.event.release.html_url }}" >> $GITHUB_STEP_SUMMARY